# @package _global_
module:
  _target_: emg2qwerty.lightning.LSTMCTCModule
  in_features: 528 # 272 #528  # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features:  [384]
  lstm_hidden_size: 128    # adjust as needed
  lstm_num_layers: [1,2,2]      # adjust as needed
  residual_connection: true
  # optimizer: ${optimizer_config}      # ensure these are defined in your config
  # lr_scheduler: ${lr_scheduler_config}  # ensure these are defined in your config
  # decoder: ${decoder_config}            # ensure these are defined in your config

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000  # 4 sec windows for 2kHz EMG
  padding: [1800, 200]  # 900ms past context, 100ms future context
