# @package _global_
module:
  _target_: emg2qwerty.lightning.LSTMCTCModule
  in_features: 528
  mlp_features: [384]
  lstm_hidden_size: 256
  lstm_num_layers: [1, 3, 3]
  residual_connection: true
  lstm_conv_params:
    - lstm_hidden_size: 256
      lstm_num_layers: 1
      conv_kernel: 3
      dropout: 0.1
      residual_connection: true
    
    - lstm_hidden_size: 256
      lstm_num_layers: 3
      conv_kernel: 3
      dropout: 0.1
      residual_connection: true

    - lstm_hidden_size: 256
      lstm_num_layers: 3
      conv_kernel: 3
      dropout: 0.1
      residual_connection: true


datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]
