# @package _global_

module:
  _target_: emg2qwerty.lightning.TransformerCTCModule
  in_features: 528
  mlp_features: [256]         # Example MLP features; adjust as needed
  transformer_params:
    num_heads: 32
    num_layers: 4
    d_model: 256
    ff_dim: 512
    dropout: 0.1

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]
