# @package _global_
downsample:
  _target_: emg2qwerty.transforms.Downsample
  factor: 4

downsample_non_integer:
  _target_: emg2qwerty.transforms.DownsampleNonInteger
  factor: 1.05
  mode: linear

slice_channels:
  _target_: emg2qwerty.transforms.SliceChannels
  indices: [0,1,2,3,4,5,6,7,8,9,10,11]

additive_gaussian_noise:
  _target_: emg2qwerty.transforms.AdditiveGaussianNoise
  mean: 0.0
  std: 0.0125

random_amplitude_scaling:
  _target_: emg2qwerty.transforms.RandomAmplitudeScaling
  scale_range: [0.7, 1.3]
  per_channel: false

to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

band_rotation:
  _target_: emg2qwerty.transforms.ForEach  # i.i.d rotation offset for each band
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets: [-1, 0, 1]

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120  # Max 60ms jitter for 2kHz EMG

logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16  # Downsamples from 2kHz to 125Hz

specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25  # Max 200ms per time mask for 125Hz spectrogram
  n_freq_masks: 2
  freq_mask_param: 4

transforms:
  train:
    - ${to_tensor}
    # - ${slice_channels}
    # - ${downsample}
    # - ${downsample_non_integer}
    - ${band_rotation}
    - ${temporal_jitter}
    # - ${random_amplitude_scaling}
    # - ${additive_gaussian_noise}
    - ${logspec}
    - ${specaug}

  val:
    - ${to_tensor}
    - ${logspec}

  test: ${transforms.val}
